package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agreement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("AgreementId")
	private java.lang.String agreementId;

	@org.kie.api.definition.type.Label(value = "PartyId")
	private java.lang.String partyId;

	@org.kie.api.definition.type.Label(value = "PersonId")
	private java.lang.String personId;

	public agreement() {
	}

	public java.lang.String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(java.lang.String agreementId) {
		this.agreementId = agreementId;
	}

	public java.lang.String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(java.lang.String partyId) {
		this.partyId = partyId;
	}

	public java.lang.String getPersonId() {
		return this.personId;
	}

	public void setPersonId(java.lang.String personId) {
		this.personId = personId;
	}

	public agreement(java.lang.String agreementId, java.lang.String partyId,
			java.lang.String personId) {
		this.agreementId = agreementId;
		this.partyId = partyId;
		this.personId = personId;
	}

}