package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "agreement")
public class agreement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("AgreementId")
	private java.lang.String agreementId;

	@org.kie.api.definition.type.Label("PartyId")
	private java.lang.String partyId;

	@org.kie.api.definition.type.Label("PersonId")
	private java.lang.String personId;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY, generator = "AGREEMENT_ID_GENERATOR")
	@javax.persistence.SequenceGenerator(name = "AGREEMENT_ID_GENERATOR", sequenceName = "AGREEMENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("processinstanceid")
	private java.lang.Long processinstanceid;

	public agreement() {
	}

	public java.lang.String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(java.lang.String agreementId) {
		this.agreementId = agreementId;
	}

	public java.lang.String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(java.lang.String partyId) {
		this.partyId = partyId;
	}

	public java.lang.String getPersonId() {
		return this.personId;
	}

	public void setPersonId(java.lang.String personId) {
		this.personId = personId;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getProcessinstanceid() {
		return this.processinstanceid;
	}

	public void setProcessinstanceid(java.lang.Long processinstanceid) {
		this.processinstanceid = processinstanceid;
	}

	public agreement(java.lang.String agreementId, java.lang.String partyId,
			java.lang.String personId, java.lang.Long id,
			java.lang.Long processinstanceid) {
		this.agreementId = agreementId;
		this.partyId = partyId;
		this.personId = personId;
		this.id = id;
		this.processinstanceid = processinstanceid;
	}

}