package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class personDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("personDetailCodeId")
	private java.lang.Integer personDetailCodeId;
	@org.kie.api.definition.type.Label("personId")
	private java.lang.Integer personId;
	@org.kie.api.definition.type.Label("deathIndicator")
	private java.lang.Boolean deathIndicator;
	@org.kie.api.definition.type.Label("bloodTypeCodeId")
	private java.lang.Integer bloodTypeCodeId;
	@org.kie.api.definition.type.Label("genderCodeId")
	private java.lang.Integer genderCodeId;
	@org.kie.api.definition.type.Label("ethnicityId")
	private java.lang.Integer ethnicityId;
	@org.kie.api.definition.type.Label("missingIndicator")
	private java.lang.Boolean missingIndicator;
	@org.kie.api.definition.type.Label("maritalStatusId")
	private java.lang.Integer maritalStatusId;
	@org.kie.api.definition.type.Label("principleMember")
	private java.lang.Boolean principleMember;
	@org.kie.api.definition.type.Label("relationshipDescriptionCodeID")
	private java.lang.Integer relationshipDescriptionCodeID;

	@org.kie.api.definition.type.Label(value = "owner")
	private java.lang.String owner;

	public personDetails() {
	}

	public java.lang.Integer getPersonDetailCodeId() {
		return this.personDetailCodeId;
	}

	public void setPersonDetailCodeId(java.lang.Integer personDetailCodeId) {
		this.personDetailCodeId = personDetailCodeId;
	}

	public java.lang.Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(java.lang.Integer personId) {
		this.personId = personId;
	}

	public java.lang.Boolean getDeathIndicator() {
		return this.deathIndicator;
	}

	public void setDeathIndicator(java.lang.Boolean deathIndicator) {
		this.deathIndicator = deathIndicator;
	}

	public java.lang.Integer getBloodTypeCodeId() {
		return this.bloodTypeCodeId;
	}

	public void setBloodTypeCodeId(java.lang.Integer bloodTypeCodeId) {
		this.bloodTypeCodeId = bloodTypeCodeId;
	}

	public java.lang.Integer getGenderCodeId() {
		return this.genderCodeId;
	}

	public void setGenderCodeId(java.lang.Integer genderCodeId) {
		this.genderCodeId = genderCodeId;
	}

	public java.lang.Integer getEthnicityId() {
		return this.ethnicityId;
	}

	public void setEthnicityId(java.lang.Integer ethnicityId) {
		this.ethnicityId = ethnicityId;
	}

	public java.lang.Boolean getMissingIndicator() {
		return this.missingIndicator;
	}

	public void setMissingIndicator(java.lang.Boolean missingIndicator) {
		this.missingIndicator = missingIndicator;
	}

	public java.lang.Integer getMaritalStatusId() {
		return this.maritalStatusId;
	}

	public void setMaritalStatusId(java.lang.Integer maritalStatusId) {
		this.maritalStatusId = maritalStatusId;
	}

	public java.lang.Boolean getPrincipleMember() {
		return this.principleMember;
	}

	public void setPrincipleMember(java.lang.Boolean principleMember) {
		this.principleMember = principleMember;
	}

	public java.lang.Integer getRelationshipDescriptionCodeID() {
		return this.relationshipDescriptionCodeID;
	}

	public void setRelationshipDescriptionCodeID(
			java.lang.Integer relationshipDescriptionCodeID) {
		this.relationshipDescriptionCodeID = relationshipDescriptionCodeID;
	}

	public java.lang.String getOwner() {
		return this.owner;
	}

	public void setOwner(java.lang.String owner) {
		this.owner = owner;
	}

	public personDetails(java.lang.Integer personDetailCodeId,
			java.lang.Integer personId, java.lang.Boolean deathIndicator,
			java.lang.Integer bloodTypeCodeId, java.lang.Integer genderCodeId,
			java.lang.Integer ethnicityId, java.lang.Boolean missingIndicator,
			java.lang.Integer maritalStatusId,
			java.lang.Boolean principleMember,
			java.lang.Integer relationshipDescriptionCodeID,
			java.lang.String owner) {
		this.personDetailCodeId = personDetailCodeId;
		this.personId = personId;
		this.deathIndicator = deathIndicator;
		this.bloodTypeCodeId = bloodTypeCodeId;
		this.genderCodeId = genderCodeId;
		this.ethnicityId = ethnicityId;
		this.missingIndicator = missingIndicator;
		this.maritalStatusId = maritalStatusId;
		this.principleMember = principleMember;
		this.relationshipDescriptionCodeID = relationshipDescriptionCodeID;
		this.owner = owner;
	}

}